name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Spec pattern (optional)
        default: cypress/e2e/**/*.cy.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run (Electron)
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: yarn install --frozen-lockfile
          browser: electron
          spec: ${{ github.event.inputs.spec }}
