name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/**/*.cy.js

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3.3.0

      - name: Cypress run (Electron)
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: yarn install --frozen-lockfile
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3.3.0

      - name: Cypress run (Chrome)
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: yarn install --frozen-lockfile
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3.3.0

      - name: Cypress run (Firefox)
        uses: cypress-io/github-action@v5.7.1
        with:
          install-command: yarn install --frozen-lockfile
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
